#---------------------------------- Achitare
1=1,1,ACHITARE
#---------------------------------- Reversari
2=2,3,ANULARE ULTIMUL CEC
3=1,6,ANULARE
4=1,11,RETURNARE
#---------------------------------- Rapoarte
8=2,10,RAPORTUL X scurt
6=2,0,RAPORTUL X detaliat
7=2,1,RAPORTUL Z
#---------------------------------- Meniu de administrare
98=2,2,MENIU CASIR
99=3,5,MENIU DE ADMINISTRARE
100=3,4,4,SESIUNE TMS
101=3,1,SINCRONIZARE TIMP
#---------------------------------- Verificare conexiunii
96=2,18,VERIFICARE CONEXIUNE
#---------------------------------- Copie cec
60=2,27,COPIE ULTIMUL CEC
62=2,26,COPIE CEC NR, INTRODUCETI NUMARUL CECULUI